### PR TITLE
lib/game: move game Universe into subpackage

### PR DESCRIPTION
**Pull request by deadprogram**
This PR moves the `Universe` into a separate subpackage so it can be used from elsewhere, such as GoBadge,

https://github.com/acifani/vita/pull/1 should be merged first and then this PR rebased.

### CODE REVIEW

**Comment by acifani** [comment]
Hey @deadprogram, thanks for the contribution! I've merged #1  so feel free to rebase this one

**Comment by acifani** [comment]
PS. Let me know if it makes it into the GoBadge, I just might build one! 😉

**Comment by deadprogram** [comment]
Rebased, thanks for the quick response @acifani 

cc @conejoninja on the badge :smile_cat:

**Comment by acifani** [comment]
@deadprogram  Merged and tagged as [v1.0.0](https://github.com/acifani/vita/releases/tag/v1.0.0). Have fun, and let me know if you run into any issues!

**Pull request merged**
